[[ -f $HOME/.config/zsh/alias.zshrc ]] && source $HOME/.config/zsh/alias.zshrc
[[ -f $HOME/.secret/secret.zshrc ]] && source $HOME/.secret/secret.zshrc
[[ -f $HOME/.config/zsh/extra.zshrc ]] && source $HOME/.config/zsh/extra.zshrc
[[ -f $HOME/.config/zsh/idf.zshrc ]] && source $HOME/.config/zsh/idf.zshrc
[[ -f $HOME/.ssh/secret/thoth.zshrc ]] && source $HOME/.ssh/secret/thoth.zshrc
[[ -f $HOME/.config/zsh/star.zshrc ]] && source $HOME/.config/zsh/star.zshrc
[[ -f $HOME/.config/zsh/ohmy.zshrc ]] && source $HOME/.config/zsh/ohmy.zshrc
[[ -f $HOME/.config/zsh/graysky.zshrc ]] && source $HOME/.config/zsh/graysky.zshrc
#[[ -f $HOME/.config/zsh/nvm.zshrc ]] && source $HOME/.config/zsh/nvm.zshrc
[[ -f $HOME/.config/zsh/randosay.zshrc ]] && source $HOME/.config/zsh/randosay.zshrc
