-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Application bindings

hl.bind("SUPER" .. " + " .. "RETURN", hl.dsp.exec_cmd("uwsm-app -- xdg-terminal-exec --dir=$(omarchy-cmd-terminal-cwd)"))

hl.bind("SUPER + ALT" .. " + " .. "RETURN", hl.dsp.exec_cmd("uwsm-app -- xdg-terminal-exec --dir=$(omarchy-cmd-terminal-cwd) bash -c tmux attach || tmux new -s Work"))

hl.bind("SUPER + SHIFT" .. " + " .. "RETURN", hl.dsp.exec_cmd("omarchy-launch-browser"))

hl.bind("SUPER + SHIFT" .. " + " .. "F", hl.dsp.exec_cmd("uwsm-app -- nautilus --new-window"))

hl.bind("SUPER + ALT + SHIFT" .. " + " .. "F", hl.dsp.exec_cmd("uwsm-app -- nautilus --new-window $(omarchy-cmd-terminal-cwd)"))

hl.bind("SUPER + SHIFT" .. " + " .. "B", hl.dsp.exec_cmd("omarchy-launch-browser"))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "B", hl.dsp.exec_cmd("omarchy-launch-browser --private"))

hl.bind("SUPER + SHIFT" .. " + " .. "M", hl.dsp.exec_cmd("omarchy-launch-or-focus spotify"))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "M", hl.dsp.exec_cmd("omarchy-launch-or-focus-tui cliamp"))

hl.bind("SUPER + SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("omarchy-launch-editor"))

hl.bind("SUPER + SHIFT" .. " + " .. "D", hl.dsp.exec_cmd("omarchy-launch-tui lazydocker"))

hl.bind("SUPER + SHIFT" .. " + " .. "G", hl.dsp.exec_cmd("omarchy-launch-or-focus ^signal$ uwsm-app -- signal-desktop"))

hl.bind("SUPER + SHIFT" .. " + " .. "O", hl.dsp.exec_cmd("omarchy-launch-or-focus ^obsidian$ uwsm-app -- obsidian"))

hl.bind("SUPER + SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("uwsm-app -- typora --enable-wayland-ime"))

hl.bind("SUPER + SHIFT" .. " + " .. "SLASH", hl.dsp.exec_cmd("uwsm-app -- 1password"))

-- If your web app url contains #, type it as ## to prevent hyprland treating it as a comment

hl.bind("SUPER + SHIFT" .. " + " .. "A", hl.dsp.exec_cmd("omarchy-launch-webapp https://chatgpt.com"))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "A", hl.dsp.exec_cmd("omarchy-launch-webapp https://grok.com"))

hl.bind("SUPER + SHIFT" .. " + " .. "C", hl.dsp.exec_cmd("omarchy-launch-webapp https://app.hey.com/calendar/weeks/"))

hl.bind("SUPER + SHIFT" .. " + " .. "E", hl.dsp.exec_cmd("omarchy-launch-webapp https://app.hey.com"))

hl.bind("SUPER + SHIFT" .. " + " .. "Y", hl.dsp.exec_cmd("omarchy-launch-webapp https://youtube.com/"))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "G", hl.dsp.exec_cmd("omarchy-launch-or-focus-webapp WhatsApp https://web.whatsapp.com/"))

hl.bind("SUPER + SHIFT + CTRL" .. " + " .. "G", hl.dsp.exec_cmd("omarchy-launch-or-focus-webapp Google Messages https://messages.google.com/web/conversations"))

hl.bind("SUPER + SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("omarchy-launch-or-focus-webapp Google Photos https://photos.google.com/"))

hl.bind("SUPER + SHIFT" .. " + " .. "X", hl.dsp.exec_cmd("omarchy-launch-webapp https://x.com/"))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "X", hl.dsp.exec_cmd("omarchy-launch-webapp https://x.com/compose/post"))

--bind = , XF86TouchpadToggle, exec, ~/.config/hypr/toggle_touchpad.sh

-- Bind directly to the libinput hardware code 532

--bindni = , code:532, exec, ~/.config/hypr/toggle_touchpad.sh

-- Add extra bindings

-- bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

-- Overwrite existing bindings, like putting Omarchy Menu on Super + Space

-- unbind = SUPER, SPACE

-- bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

-- Logitech MX Keys

-- bind = SUPER SHIFT, S, exec, omarchy-capture-screenshot      # Print Screen Button

-- bind = SUPER, H, exec, voxtype record toggle                 # Dictation Button

-- bind = SUPER, PERIOD, exec, omarchy-launch-walker -m symbols # Emoji Button
