-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- New Hyprland Gesture Declarations

-- TODO: manual review: gesture = 3, "horizontal", "workspace"

-- Optional Global Tuning Rules

hl.config({
    gestures = {
        workspace_swipe_distance = 300,
        workspace_swipe_invert = true,
        workspace_swipe_create_new = true,
    },
})
