-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local kb_bl = "asus::kbd_backlight"

hl.config({
    general = {
        lock_cmd = "omarchy-system-lock",
        -- lock screen and 1password
        before_sleep_cmd = "OMARCHY_LOCK_ONLY=true omarchy-system-lock",
        -- lock before suspend without scheduling display off.
        after_sleep_cmd = "sleep 1 && omarchy-system-wake",
        -- delay for PAM readiness, then turn on display.
        inhibit_sleep = 3,
        -- wait until screen is locked
    },
})

-- Start screensaver after 2.5 minutes

hl.config({
    listener = {
        timeout = 150,
        on-timeout = "pidof hyprlock || omarchy-launch-screensaver",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- Lock system after 5 minutes (screensaver resets idle timer, so have to just do half + 2s margin)

hl.config({
    listener = {
        timeout = 152,
        on-timeout = "omarchy-system-lock",
        on-resume = "omarchy-system-wake",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 150,
        -- 2.5min.
        on-timeout = "brightnessctl -s set 10",
        -- set monitor backlight to minimum, avoid 0 on OLED monitor.
        on-resume = "brightnessctl -r",
        -- monitor backlight restore.
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 180,
        on-timeout = "pidof hyprlock || omarchy-launch-screensaver",
        -- start screensaver (if we haven't locked already)
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.

hl.config({
    listener = {
        timeout = 170,
        -- 2.5min.
        on-timeout = "brightnessctl -sd asus::kbd_backlight set 0",
        -- turn off keyboard backlight.
        on-resume = "brightnessctl -rd asus::kbd_backlight",
        -- turn on keyboard backlight.
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- listener {

-- timeout = 300                                 # 5min

-- on-timeout = loginctl lock-session            # lock screen when timeout has passed

-- }

hl.config({
    listener = {
        timeout = 210,
        -- 5min
        on-timeout = "loginctl lock-session",
        -- lock screen when timeout has passed
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 660,
        -- 5.5min0
        on-timeout = "hyprctl dispatch dpms off",
        -- screen off when timeout has passed
        on-resume = "hyprctl dispatch dpms on && brightnessctl -r",
        -- screen on when activity is detected
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 1800,
        -- 30min
        on-timeout = "systemctl hibernate",
        -- suspend pc
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output
