-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    input = {
        kb_layout = "us",
        kb_options = "compose:caps",
        repeat_rate = 40,
        repeat_delay = 250,
        numlock_by_default = true,
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
            clickfinger_behavior = true,
            scroll_factor = 0.4,
            tap-to-click = true,
            clickfinger_behavior = false,
            disable_while_typing = true,
        },
    },
})

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

-- 

-- device {

--     name = elan0542:00-04f3:3368-mouse

--     enabled = false

-- }

-- 

-- device {

--     name = elan0542:00-04f3:3368-touchpad

--     enabled = true

--     accel_profile = adaptive

--     sensitivity = 0.35

-- }

-- 

hl.device({
    name = "lenovo-350-bluetooth-silent-mouse",
    left_handed = true,
})

-- Force-inject the working bracket commands into the compositor startup sequence

--exec-once = hyprctl keyword "device[elan0542:00-04f3:3368-mouse]:enabled" false

--exec-once = hyprctl keyword "device[elan0542:00-04f3:3368-touchpad]:enabled" true

--exec-once = hyprctl keyword "device[elan0542:00-04f3:3368-touchpad]:sensitivity" 0.35

hl.device({
    name = "lenovo-ms-mouse",
    left_handed = true,
})

hl.device({
    name = "pixart-cyberpower-opticalmouse",
    left_handed = true,
})

hl.device({
    name = "kensington-eagle-trackball",
    left_handed = true,
})
