-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- >>> hyprmon:begin >>> (auto-generated — do not edit between markers)

hl.monitor({
    output   = "desc:Dell Inc. DELL P190S",
    mode     = "1280x1024@60.02",
    position = "0x0",
    scale    = 1,
    transform = 1,
})

hl.monitor({
    output   = "eDP-1",
    mode     = "2880x1800@120.00",
    position = "0x0",
    scale    = 2,
})

hl.monitor({
    output   = "eDP-2",
    mode     = "2560x1600@165.00",
    position = "1024x0",
    scale    = 1.50,
})

-- Fallback for unknown monitors

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

-- <<< hyprmon:end <<<
